version: '3.8'

services:
  home-walkie-talkie:
    build: .
    container_name: home-walkie-talkie
    restart: unless-stopped
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
